"""Reasoning Adapter — the LLM behind the Reasoning Engine Port.

The Reasoning Engine already exposes a ``ReasoningEnginePort`` (Phase 4, ReL1: a
faculty *above* substitutable engines). This adapter is one such engine — it does not
build a new LLM; it invokes the **existing Ollama client** (Qwen / DeepSeek / Llama)
through the injected ``LLMPort``. The Reasoning Engine invokes the port; the port
invokes Ollama; the faculty keeps its confidence, consistency, trace, and state
discipline unchanged. On LLM failure it returns ``None`` so the faculty degrades
gracefully (ReL14).
"""

from __future__ import annotations

from typing import Any

from app.cognitive_kernel.engines.reasoning.contracts import (
    EngineProduct,
    EngineRequest,
    ReasoningType,
)
from app.cognitive_kernel.engines.reasoning.pool import EnginePool

from .ports import LLMPort

_SYSTEM = (
    "You are the reasoning faculty of a governed cognitive operating system. "
    "Answer the user's query directly, concisely, and factually. Use the provided "
    "known facts and your knowledge; do not fabricate. If unsure, say so plainly."
)


class OllamaReasoningEngine:
    """A substitutable reasoning engine backed by the existing Ollama infrastructure."""

    name = "generative_llm"
    handles = frozenset(ReasoningType)  # the generative engine can serve any reasoning type

    def __init__(self, llm: LLMPort, *, model: str | None = None, temperature: float = 0.3,
                 confidence: float = 0.85) -> None:
        self._llm = llm
        self._model = model
        self._temperature = temperature
        self._confidence = confidence

    def propose(self, request: EngineRequest, context: Any) -> EngineProduct | None:
        query = request.question or request.goal
        if not query:
            return None
        facts = "\n".join(f"- {e.statement}" for e in request.evidence) or "(no prior facts in focus)"
        prompt = (
            f"Goal / query: {query}\n"
            f"Facts currently in conscious focus:\n{facts}\n\n"
            f"Provide a direct, helpful answer."
        )
        try:
            answer = self._llm.complete(prompt, system=_SYSTEM, model=self._model,
                                        temperature=self._temperature)
        except Exception:
            return None  # graceful degradation — the faculty falls back (ReL14)
        answer = (answer or "").strip()
        if not answer:
            return None
        return EngineProduct(
            engine=self.name, statement=answer, negated=False, confidence=self._confidence,
            justification="generated by the Reasoning Engine Port (Ollama)", rtype=request.rtype,
        )


def build_reasoning_pool(llm: LLMPort, *, model: str | None = None) -> EnginePool:
    """A pool whose sole engine is the Ollama-backed port — every reasoning step
    routes to the LLM through the faculty. (The deterministic engines remain available
    for other sessions; here the chat slice reasons generatively.)"""
    pool = EnginePool()
    pool.register(OllamaReasoningEngine(llm, model=model))
    return pool
