"""M19 Event Bus — decoupled control-plane notification.

Enables upward communication without upward dependencies (01_LAYERED §2).
"""

from __future__ import annotations

from .bus import BusStats, DeliveryPolicy, EventBus, OverflowPolicy, Subscription
from .events import (
    ALL_EVENT_TYPES,
    AssociationFailure,
    BudgetExceeded,
    CameraChanged,
    CanaryPromoted,
    ClockQualityChanged,
    ConfigChanged,
    CoverageChanged,
    DecodeFailed,
    DetectionCompleted,
    DetectionFailed,
    DetectorLoaded,
    DetectorUnloaded,
    DevicePressure,
    EpochAdvanced,
    Event,
    FrameEvicted,
    Gap,
    HealthChanged,
    LeaseLeaked,
    MaskFailure,
    ModelEvicted,
    ModelLoaded,
    ModelSwapped,
    PerformanceWarning,
    PipelineAttached,
    PipelineDetached,
    PluginLoaded,
    PluginRejected,
    PoolPressure,
    SilentFailureSuspected,
    StreamConnected,
    StreamLost,
    SustainedDropAlarm,
    ThresholdExceeded,
    TrackCreated,
    TrackerEpochAdvanced,
    TrackerLoaded,
    TrackerUnloaded,
    TrackingWarning,
    TrackLost,
    TrackRecovered,
    TrackTerminated,
    TrackUpdated,
    ViewpointDriftSuspected,
)

__all__ = [
    "ALL_EVENT_TYPES",
    "AssociationFailure",
    "BudgetExceeded",
    "BusStats",
    "CameraChanged",
    "CanaryPromoted",
    "ClockQualityChanged",
    "ConfigChanged",
    "CoverageChanged",
    "DecodeFailed",
    "DeliveryPolicy",
    "DetectionCompleted",
    "DetectionFailed",
    "DetectorLoaded",
    "DetectorUnloaded",
    "DevicePressure",
    "EpochAdvanced",
    "Event",
    "EventBus",
    "FrameEvicted",
    "Gap",
    "HealthChanged",
    "LeaseLeaked",
    "MaskFailure",
    "ModelEvicted",
    "ModelLoaded",
    "ModelSwapped",
    "OverflowPolicy",
    "PerformanceWarning",
    "PipelineAttached",
    "PipelineDetached",
    "PluginLoaded",
    "PluginRejected",
    "PoolPressure",
    "SilentFailureSuspected",
    "StreamConnected",
    "StreamLost",
    "Subscription",
    "SustainedDropAlarm",
    "ThresholdExceeded",
    "TrackCreated",
    "TrackLost",
    "TrackRecovered",
    "TrackTerminated",
    "TrackUpdated",
    "TrackerEpochAdvanced",
    "TrackerLoaded",
    "TrackerUnloaded",
    "TrackingWarning",
    "ViewpointDriftSuspected",
]
